# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcd378fdd89f336961bce590bdf2be6e6e15ed42b9f51d6f8c3795886a90f1ed724cba78834895fdf85a66b57121b45722367486c3bd5619c1e2193bf417b129

test:
  secret_key_base: 6362f3e35ea0f3160dd47da2a7463f36c2351d937877c6d07493b1c32f8b878f6cbb06675286a8ca38d0c032fa055cd177f1bea23b3a60541a2e4b6a75dce436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
